[[IgnoredVulns]]
id = "GHSA-h5c3-5r3r-rr8q"
reason = "Untrusted headers are not processed"

[[IgnoredVulns]]
id = "GHSA-rmvr-2pp2-xj38"
reason = "Untrusted headers are not processed"

[[IgnoredVulns]]
id = "GHSA-xx4v-prfh-6cgc"
reason = "Untrusted headers are not processed"

[[IgnoredVulns]]
id = "GHSA-67mh-4wv8-2f99"
reason = "It is a a test dependency"

[[IgnoredVulns]]
id = "GHSA-g4jq-h2w9-997c"
reason = "It is only used for testing"

[[IgnoredVulns]]
id = "GHSA-jqfw-vq24-v9c3"
reason = "It is only used for testing"
